#!/bin/bash

mkdir -p /data

## Bump php upload max filesize and post max size to 100MB by default
grep -qF 'upload_max_filesize' /config/php/php-local.ini || echo 'upload_max_filesize = 200M' >> /config/php/php-local.ini
grep -qF 'post_max_size' /config/php/php-local.ini || echo 'post_max_size = 200M' >> /config/php/php-local.ini

touch /config/settings.php
ln -sf /config/settings.php /app/www/public/app/settings.php

[[ ! -e "/data/images" ]] &&
    mv /app/www/public/images /data

rm -rf /app/www/public/images
ln -sf /data/images /app/www/public/images

chown -R abc:abc \
    /app/www/public \
    /config \
    /data
