#!/bin/bash

mkdir -p /data

# copy config
[[ ! -e /config/user.ini ]] && \
	cp /defaults/user.ini /config/user.ini
cp /config/user.ini /etc/php7/conf.d/99-user.ini

touch /config/settings.php
ln -sf /config/settings.php /app/chevereto/app/settings.php

[[ ! -e "/data/images" ]] &&
    mv /app/chevereto/images /data

rm -rf /app/chevereto/images
ln -sf /data/images /app/chevereto/images

chown -R abc:abc \
    /app/chevereto \
    /config \
    /data
