#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

We recommend alternative images such as:
https://github.com/linuxserver/docker-pixapop/
https://github.com/linuxserver/docker-piwigo/
https://github.com/linuxserver/docker-photoshow/


******************************************************
******************************************************'
